name: myapp
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  IMAGE_TAG: teplodizain/savchenko-test-container
  RELEASE_NAME: myapp
  NAMESPACE: syte

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    
# действие позволяет получить доступ к коду из репозитория в контексте рабочего процесса.
      - name: Checkout
        uses: actions/checkout@v4 
        
# автоматизирует процесс входа в реестр Docker. 
#Это позволяет аутентифицировать операции с Docker без ручного ввода учётных данных каждый раз
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PAS }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from commit messages
        run: |
          VERSION=$(git log -1 --pretty=format:%B)
          if [[ ! -z "$VERSION" ]]; then
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No version found in the commit message"
            exit 1
          fi
          
# автоматизирует сборку и push Docker-образов
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}

  deploy:
    needs: build-and-push
    name: Deploy to Kubernetes
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
#  выкачивает репозиторий и встаёт на нужный коммит
      - name: Checkout code
        uses: actions/checkout@v2

# устанавливает определённую версию kubectl в средстве выполнения
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0'

# Извлекать версию из сообщений о фиксации
      - name: Extract version from commit messages
        run: |
          VERSION=$(git log -1 --pretty=format:%B)
          if [[ ! -z "$VERSION" ]]; then
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No version found in the commit message"
            exit 1
          fi
          
# Замените тег изображения в файле deploy.yaml
      - name: Replace image tag in deploy.yaml
        if: env.DEPLOY == 'false'
       
        run: |
          sed -i "s|image: teplodizain/savchenko-test-container:.*|image: ${{ env.IMAGE_TAG }}|" ./myapp/deploy.yaml
        env:
          IMAGE_TAG: teplodizain/savchenko-test-container:${{ env.VERSION }}
#          IMAGE_TAG: teplodizain/savchenko-test-container:2.3

      
      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube/
      - name: Authenticate to Kubernetes cluster
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > ${HOME}/.kube/config
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./myapp/deploy.yaml 
